server:
  port: 8080
spring:
  application:
    name: "order"
  datasource:
    url: "jdbc:h2:file:~/order;AUTO_SERVER=true"
    driver-class-name: "org.h2.Driver"
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "order-service"
    description: "E-Commerce Order Application"
    version: "1.0.0"

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

axon:
  eventhandling:
    processors:
      order-group:
        mode: subscribing
      order-saga-group:
        mode: tracking
        initial-segment-count: 1
  axonserver:
    servers: localhost:8124